apiVersion: v1
kind: Pod
metadata:
  name: fio-client
  namespace: simple-fio
spec:
  containers:
    - image: quay.io/abose/fio:latest
      name: fio-client
      command: ["/bin/sh", "-c"]
      args:
        - "echo *********Fio_Job**************;
          dnf install wget -y;
          wget https://raw.githubusercontent.com/bose-abhishek/odf-dr-fio/main/fio.job;
          /usr/bin/fio --client=fio-server fio.job;
          sleep 10;
          grep -A6 \"All clients\" /tmp/output.log;
          sleep 60;
          "
  initContainers:
    - name: init-service
      image: quay.io/abose/fio:latest
      command: ['sh', '-c', "dnf install dnsutils -y; until nslookup fio-server; do echo waiting for fio-server; sleep 10; done"]
  restartPolicy: Never
