apiVersion: v1
kind: Service
metadata:
  name: fio-server
  namespace: odf-dr-fio
  labels:
    app: fio-server
spec:
  ports:
  - port: 8765
    name: fio-server
  clusterIP: None
  selector:
    app: fio-server
